@LunchAndLearn_HostAddress = http://localhost:5099

### Get all issues
GET {{LunchAndLearn_HostAddress}}/issues
Accept: application/json

### Get only HIGH priority issues
GET {{LunchAndLearn_HostAddress}}/issues?priority=high
Accept: application/json

### Get only MEDIUM priority issues
GET {{LunchAndLearn_HostAddress}}/issues?priority=medium
Accept: application/json

### Get only LOW priority issues
GET {{LunchAndLearn_HostAddress}}/issues?priority=low
Accept: application/json

###
