@LunchAndLearn_HostAddress = http://localhost:5099

### Get all issues
GET {{LunchAndLearn_HostAddress}}/issues
Accept: application/json

### Get only HIGH priority issues
GET {{LunchAndLearn_HostAddress}}/issues?priority=HIGH
Accept: application/json

### Get only LOW priority issues
GET {{LunchAndLearn_HostAddress}}/issues?priority=LOW
Accept: application/json

###
